from __future__ import annotations

"""
Display Module (PRE-BUILT)
============================
DO NOT EDIT THIS FILE -- provides rich display utilities for the GPU Job Scheduler.

Uses the ``rich`` library to render cluster info, job lists, dependency graphs,
live job status updates, and a final summary.
"""

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.text import Text

from sdk_do_not_edit import ClusterInfo, Job

console = Console()


# ---------------------------------------------------------------------------
# Cluster info
# ---------------------------------------------------------------------------

def display_cluster_info(cluster: ClusterInfo) -> None:
    """Display a table showing cluster nodes and GPU availability."""
    if cluster is None:
        console.print("[yellow]No cluster info available.[/yellow]")
        return

    table = Table(title="GPU Cluster", border_style="cyan")
    table.add_column("Node", style="bold")
    table.add_column("Total GPUs", justify="center")
    table.add_column("Available GPUs", justify="center")

    for node in cluster.nodes:
        avail_style = "green" if node.available_gpus > 0 else "red"
        table.add_row(
            node.id,
            str(node.total_gpus),
            f"[{avail_style}]{node.available_gpus}[/{avail_style}]",
        )

    table.add_section()
    table.add_row("[bold]Total[/bold]", str(cluster.total_gpus), str(cluster.total_gpus))

    console.print(table)
    console.print()


# ---------------------------------------------------------------------------
# Job list
# ---------------------------------------------------------------------------

def display_job_list(jobs: list[Job]) -> None:
    """Display all jobs with their dependencies, priorities, and GPU requirements."""
    if not jobs:
        console.print("[yellow]No jobs to display.[/yellow]")
        return

    table = Table(title="Pending Jobs", border_style="magenta")
    table.add_column("Job ID", style="bold")
    table.add_column("Name")
    table.add_column("Priority", justify="center")
    table.add_column("GPUs", justify="center")
    table.add_column("Dependencies")
    table.add_column("Est. Duration", justify="right")

    priority_colors = {5: "red", 4: "yellow", 3: "green", 2: "cyan", 1: "blue"}

    for job in jobs:
        p_color = priority_colors.get(job.priority, "white")
        deps = ", ".join(job.dependencies) if job.dependencies else "[dim]none[/dim]"
        table.add_row(
            job.id,
            job.name,
            f"[{p_color}]{job.priority}[/{p_color}]",
            str(job.gpu_count),
            deps,
            f"{job.estimated_duration_ms}ms",
        )

    console.print(table)
    console.print()


# ---------------------------------------------------------------------------
# Dependency graph (ASCII art)
# ---------------------------------------------------------------------------

def display_dependency_graph(jobs: list[Job]) -> None:
    """Render an ASCII-art dependency graph of the job DAG."""
    if not jobs:
        console.print("[yellow]No jobs for dependency graph.[/yellow]")
        return

    job_map = {j.id: j for j in jobs}

    # Assign levels via BFS (longest path from roots)
    in_degree: dict[str, int] = {j.id: 0 for j in jobs}
    children: dict[str, list[str]] = {j.id: [] for j in jobs}
    for j in jobs:
        for dep in j.dependencies:
            children[dep].append(j.id)
            in_degree[j.id] += 1

    level: dict[str, int] = {}
    queue = [jid for jid, deg in in_degree.items() if deg == 0]
    for jid in queue:
        level.setdefault(jid, 0)

    visited = set()
    frontier = list(queue)
    while frontier:
        next_frontier = []
        for jid in frontier:
            if jid in visited:
                continue
            visited.add(jid)
            for child in children[jid]:
                level[child] = max(level.get(child, 0), level[jid] + 1)
                next_frontier.append(child)
        frontier = next_frontier

    # Group by level
    levels: dict[int, list[str]] = {}
    for jid, lv in level.items():
        levels.setdefault(lv, []).append(jid)

    max_level = max(levels.keys()) if levels else 0

    lines: list[str] = []
    lines.append("Job Dependency Graph (DAG)")
    lines.append("=" * 60)

    for lv in range(max_level + 1):
        jids = sorted(levels.get(lv, []))
        tags = []
        for jid in jids:
            j = job_map[jid]
            gpu_tag = f"[{j.gpu_count}G]"
            pri_tag = f"P{j.priority}"
            tags.append(f"{jid} {gpu_tag} {pri_tag}")
        row = "  |  ".join(tags)
        lines.append(f"  Level {lv}:  {row}")
        if lv < max_level:
            lines.append("           " + "|")
            lines.append("           " + "v")

    lines.append("=" * 60)

    panel_text = "\n".join(lines)
    console.print(Panel(panel_text, title="Dependency Graph", border_style="green"))
    console.print()


# ---------------------------------------------------------------------------
# Live job update
# ---------------------------------------------------------------------------

_STATUS_STYLES = {
    "PENDING": "dim",
    "READY": "cyan",
    "ACQUIRING": "yellow",
    "RUNNING": "blue",
    "COMPLETED": "green",
    "FAILED": "red",
    "RETRYING": "yellow",
}


def display_job_update(job_id: str, status: str, node: str, message: str) -> None:
    """Print a single job status update line with colour coding."""
    style = _STATUS_STYLES.get(status, "white")
    node_part = f" @ {node}" if node else ""
    console.print(
        f"  [{style}][{status:^11}][/{style}]  "
        f"[bold]{job_id}[/bold]{node_part}  {message}"
    )


# ---------------------------------------------------------------------------
# Final summary
# ---------------------------------------------------------------------------

def display_final_summary(results: dict) -> None:
    """
    Display a summary table at the end of the run.

    Expected *results* shape::

        {
            "total_jobs": int,
            "completed": int,
            "failed": int,
            "total_time": float,
            "job_results": [
                {"job_id": str, "status": str, "duration_ms": int,
                 "node": str, "retries": int},
                ...
            ],
            "gpu_utilization": float,
        }
    """
    if not results:
        console.print("[yellow]No results to display.[/yellow]")
        return

    console.print()
    console.rule("[bold]Execution Summary[/bold]", style="cyan")
    console.print()

    # Overview
    overview = Table(show_header=False, border_style="cyan", padding=(0, 2))
    overview.add_column("Metric", style="bold")
    overview.add_column("Value")

    total = results.get("total_jobs", 0)
    completed = results.get("completed", 0)
    failed = results.get("failed", 0)
    total_time = results.get("total_time", 0.0)
    utilization = results.get("gpu_utilization", 0.0)

    overview.add_row("Total Jobs", str(total))
    c_style = "green" if completed == total else "yellow"
    overview.add_row("Completed", f"[{c_style}]{completed}[/{c_style}]")
    f_style = "green" if failed == 0 else "red"
    overview.add_row("Failed", f"[{f_style}]{failed}[/{f_style}]")
    overview.add_row("Total Time", f"{total_time:.2f}s")
    overview.add_row("GPU Utilization", f"{utilization:.1%}")

    console.print(overview)
    console.print()

    # Per-job table
    job_results = results.get("job_results", [])
    if job_results:
        table = Table(title="Job Results", border_style="magenta")
        table.add_column("Job ID", style="bold")
        table.add_column("Status", justify="center")
        table.add_column("Duration", justify="right")
        table.add_column("Node")
        table.add_column("Retries", justify="center")

        for jr in job_results:
            status = jr.get("status", "UNKNOWN")
            s_style = _STATUS_STYLES.get(status, "white")
            dur = jr.get("duration_ms", 0)
            table.add_row(
                jr.get("job_id", "?"),
                f"[{s_style}]{status}[/{s_style}]",
                f"{dur}ms" if dur else "-",
                jr.get("node", "-"),
                str(jr.get("retries", 0)),
            )

        console.print(table)

    console.print()
