from __future__ import annotations

"""
Mocked GPU Cluster SDK
========================
DO NOT EDIT THIS FILE -- it simulates a GPU cluster management API.

This SDK provides access to a simulated GPU cluster with 4 nodes,
each having 2 GPUs (8 total). Jobs can request 1-2 GPUs.

Classes:
    GpuClusterSDK - Main SDK client
    ClusterInfo - Cluster configuration
    NodeInfo - Node details (id, total_gpus, available_gpus)
    Job - A training job (id, name, priority 1-5, gpu_count 1-2,
          dependencies list[str], estimated_duration_ms)
    JobResult - Result of job execution (job_id, success, duration_ms, error_msg)
    GpuAllocation - Allocation info (job_id, node_id, gpu_count)
    JobStatus - Enum: PENDING, READY, RUNNING, COMPLETED, FAILED
    InsufficientResourcesError - Raised when not enough GPUs
    JobExecutionError - Raised when job execution fails

Methods:
    get_cluster_info() -> ClusterInfo
        Returns cluster with 4 nodes, 2 GPUs each. ~50ms delay.

    list_pending_jobs() -> list[Job]
        Returns 12 jobs with priorities, dependencies, GPU requirements. ~100ms delay.
        Jobs form a realistic DAG (some depend on others, no cycles).

    allocate_gpus(node_id: str, gpu_count: int, job_id: str) -> GpuAllocation
        Allocates GPUs on a node. ~50ms delay.
        Raises InsufficientResourcesError if not enough available.
        Raises ValueError if node_id not found.

    release_gpus(allocation: GpuAllocation) -> None
        Releases previously allocated GPUs. ~30ms delay.

    execute_job(job_id: str, allocation: GpuAllocation) -> JobResult
        Runs the job. Takes 300-1500ms. ~15% chance of failure.
        Returns JobResult with success=True/False.
        Raises JobExecutionError on catastrophic failure (~5% chance).
"""

import time
import random
import threading
from dataclasses import dataclass, field
from enum import Enum


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class InsufficientResourcesError(Exception):
    """Raised when not enough GPUs are available on the requested node."""
    pass


class JobExecutionError(Exception):
    """Raised when a job execution fails catastrophically."""
    pass


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class JobStatus(Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class NodeInfo:
    id: str
    total_gpus: int
    available_gpus: int


@dataclass
class ClusterInfo:
    nodes: list[NodeInfo]
    total_gpus: int


@dataclass
class Job:
    id: str
    name: str
    priority: int  # 1-5, higher = more important
    gpu_count: int  # 1 or 2
    dependencies: list[str] = field(default_factory=list)
    estimated_duration_ms: int = 500


@dataclass
class JobResult:
    job_id: str
    success: bool
    duration_ms: int
    error_msg: str | None = None


@dataclass
class GpuAllocation:
    job_id: str
    node_id: str
    gpu_count: int


# ---------------------------------------------------------------------------
# SDK
# ---------------------------------------------------------------------------

class GpuClusterSDK:
    """Simulated GPU Cluster SDK. Thread-safe internally."""

    def __init__(self):
        self._lock = threading.Lock()
        # Internal GPU tracking per node
        self._node_gpus: dict[str, int] = {
            "node-1": 2,
            "node-2": 2,
            "node-3": 2,
            "node-4": 2,
        }
        self._total_gpus = 8

    # ------- Cluster info ---------------------------------------------------

    def get_cluster_info(self) -> ClusterInfo:
        """Return cluster topology. ~50ms simulated latency."""
        time.sleep(0.05)
        with self._lock:
            nodes = [
                NodeInfo(id=nid, total_gpus=2, available_gpus=avail)
                for nid, avail in self._node_gpus.items()
            ]
        return ClusterInfo(nodes=nodes, total_gpus=self._total_gpus)

    # ------- Job listing ----------------------------------------------------

    def list_pending_jobs(self) -> list[Job]:
        """Return the 12-job DAG. ~100ms simulated latency."""
        time.sleep(0.1)
        return [
            Job(
                id="data-preprocess",
                name="Data Preprocessing",
                priority=5,
                gpu_count=1,
                dependencies=[],
                estimated_duration_ms=600,
            ),
            Job(
                id="tokenizer-train",
                name="Tokenizer Training",
                priority=4,
                gpu_count=1,
                dependencies=["data-preprocess"],
                estimated_duration_ms=800,
            ),
            Job(
                id="embedding-train",
                name="Embedding Training",
                priority=4,
                gpu_count=1,
                dependencies=["data-preprocess"],
                estimated_duration_ms=700,
            ),
            Job(
                id="base-model-train",
                name="Base Model Training",
                priority=5,
                gpu_count=2,
                dependencies=["tokenizer-train", "embedding-train"],
                estimated_duration_ms=1200,
            ),
            Job(
                id="finetune-classification",
                name="Finetune Classification",
                priority=3,
                gpu_count=1,
                dependencies=["base-model-train"],
                estimated_duration_ms=900,
            ),
            Job(
                id="finetune-generation",
                name="Finetune Generation",
                priority=3,
                gpu_count=2,
                dependencies=["base-model-train"],
                estimated_duration_ms=1000,
            ),
            Job(
                id="finetune-qa",
                name="Finetune QA",
                priority=3,
                gpu_count=1,
                dependencies=["base-model-train"],
                estimated_duration_ms=800,
            ),
            Job(
                id="eval-classification",
                name="Eval Classification",
                priority=2,
                gpu_count=1,
                dependencies=["finetune-classification"],
                estimated_duration_ms=500,
            ),
            Job(
                id="eval-generation",
                name="Eval Generation",
                priority=2,
                gpu_count=1,
                dependencies=["finetune-generation"],
                estimated_duration_ms=500,
            ),
            Job(
                id="eval-qa",
                name="Eval QA",
                priority=2,
                gpu_count=1,
                dependencies=["finetune-qa"],
                estimated_duration_ms=500,
            ),
            Job(
                id="merge-results",
                name="Merge Results",
                priority=1,
                gpu_count=1,
                dependencies=["eval-classification", "eval-generation", "eval-qa"],
                estimated_duration_ms=400,
            ),
            Job(
                id="deploy-model",
                name="Deploy Model",
                priority=1,
                gpu_count=2,
                dependencies=["merge-results"],
                estimated_duration_ms=600,
            ),
        ]

    # ------- GPU allocation -------------------------------------------------

    def allocate_gpus(self, node_id: str, gpu_count: int, job_id: str) -> GpuAllocation:
        """
        Allocate *gpu_count* GPUs on *node_id* for *job_id*.

        ~50ms simulated latency.
        Raises ValueError if node_id is unknown.
        Raises InsufficientResourcesError if not enough GPUs.
        """
        time.sleep(0.05)
        with self._lock:
            if node_id not in self._node_gpus:
                raise ValueError(f"Unknown node: {node_id}")
            if self._node_gpus[node_id] < gpu_count:
                raise InsufficientResourcesError(
                    f"Node {node_id} has {self._node_gpus[node_id]} GPUs available, "
                    f"but {gpu_count} requested for job {job_id}"
                )
            self._node_gpus[node_id] -= gpu_count
        return GpuAllocation(job_id=job_id, node_id=node_id, gpu_count=gpu_count)

    def release_gpus(self, allocation: GpuAllocation) -> None:
        """Release GPUs from an allocation. ~30ms simulated latency."""
        time.sleep(0.03)
        with self._lock:
            if allocation.node_id in self._node_gpus:
                self._node_gpus[allocation.node_id] += allocation.gpu_count

    # ------- Job execution --------------------------------------------------

    def execute_job(self, job_id: str, allocation: GpuAllocation) -> JobResult:
        """
        Execute a job. Takes 300-1500ms.
        ~15% chance of returning success=False.
        ~5% chance of raising JobExecutionError.
        """
        duration_ms = int(random.uniform(300, 1500))
        time.sleep(duration_ms / 1000.0)

        roll = random.random()

        # ~5% catastrophic failure
        if roll < 0.05:
            raise JobExecutionError(
                f"Catastrophic failure executing job {job_id} on {allocation.node_id}"
            )

        # ~15% soft failure (includes the 5% above, so effective soft-only is 10%)
        if roll < 0.15:
            return JobResult(
                job_id=job_id,
                success=False,
                duration_ms=duration_ms,
                error_msg=f"Job {job_id} failed: simulated training error",
            )

        return JobResult(
            job_id=job_id,
            success=True,
            duration_ms=duration_ms,
            error_msg=None,
        )
